---
title: Baby Names and Gender Associations
author: Lief Esbenhsade
date: '2019-06-14'
slug: names-and-sex
categories:
  - baby-names
tags:
  - side
subtitle: '[A Baby Names Post](/project/baby-names/baby-names)'
summary: 'How names are associated with boys or girls'
lastmod: '2019-06-14T15:07:23-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
draft: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')

library(tidyverse)

project_dir <- source("project_dir.R")[[1]]

df <- readRDS(paste0(project_dir, "/name_data.rds"))
df2 <- df %>% 
  spread(Sex, Count, fill = 0) %>% 
  mutate(total = F+M, 
         p_F = F / (total))
```

## Gender Neutral Names in 2017

```{r}
neutral <- df2 %>%
  filter(Year == 2017, 
         p_F > .4 & p_F < .6,
         total > 100) %>% 
  arrange(desc(total))
```
There are surprisingly few gender neutral names in 2017. I find only `r nrow(neutral)` names that are given to at least 100 kids and are between 40 and 60 \% female. The ten most popular gender neutral names are listed below. 

```{r}

ptile <- df2 %>% 
  mutate(p = round(p_F*10,1)) %>% 
  group_by(p) %>% 
  summarize(count = sum(total), 
            F = sum(F),
            M = sum(M)) %>% 
  mutate(pos = cumsum(count) - count)
    
# ggplot(data = ptile) +
#   geom_mosaic(aes(weight = Count, x = p, fill = F))

# ggplot() +
# geom_mosaic(aes(weight = n.cases, x = product(number), 
#               fill = factor(n.cases)), offset = 0) 
 
```


```{r}
knitr::kable(neutral %>% select(Name, "Total Babies" = total, "Percent Female" = p_F) %>% head(10), digits = 2)
```


## Boys to Girls
```{r}
df3 <- df2 %>% 
  group_by(Name, Decade) %>% 
  summarize(p_F = weighted.mean(p_F, total),
            total = sum(total)) %>% 
  ungroup()
df4 <- df3 %>%   
  filter(total > 100) %>% 
  group_by(Name) %>% 
  summarize(min = min(p_F, na.rm=T), 
            max = max(p_F, na.rm=T), 
            total = sum(total, na.rm=T), 
            delta = max - min) %>% 
  arrange(desc(delta)) 
```
 
```{r}
knitr::kable(df4 %>% filter(total > 10000) %>% head(10))
```

## Girls to Boys??
